apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: first
    http:
      paths:
      - pathType: Exact
        path: /wear
        backend:
          service:
            name: service-name-here
            port:
              number: 80
#  - host: second
