apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wear-watch
spec:
  rules:
  - http:
      paths:
      - path: "/wear"
        pathType: "Exact"
        backend:
          service:
            name: wear-service
            port:
              number: 80
      - path: "/watch"
        pathType: "Exact"
        backend:
          service:
            name: watch-service
            port:
              number: 80
