apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: whatwhat
    image: busybox
    command: ["sleep"]
    args: ["3600"]
    resources:
      requests:
        cpu: 100m
        memory: 5M
      limits:
        cpu: 200m
        memory: 200M

