apiVersion: v1
kind: Pod
metadata:
  name: whatwhat
spec:
  containers:
  - name: whatwhat
    image: busybox
    command: ["sleep"]
    args: ["3600"]
    envFrom:
    - secretRef:
        name: "my-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  login: bG9naW4=
  pw: cGFzc3dvcmRkZGRk

