apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvviewer-rb
subjects:
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pvviewer-cr
  apiGroup: rbac.authorization.k8s.io
