apiVersion: v1
kind: Secret
metadata:
  name: secret-new
data:
  login: bG9naW4=
  pass: cGFzcw==
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-new
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: secret-new

